
const LocationOptions = [
    { value: 'Bangkok', label: 'Bangkok' },
    { value: 'Kamphaeng Phet', label: 'Kamphaeng Phet' },
    { value: 'Chai Nat', label: 'Chai Nat' },
    { value: 'Nakhon Nayok', label: 'Nakhon Nayok' },
    { value: 'Nakhon Pathom', label: 'Nakhon Pathom' },
    { value: 'Nakhon Sawan', label: 'Nakhon Sawan' },
    { value: 'Nonthaburi', label: 'Nonthaburi' },
    { value: 'Pathum Thani ', label: 'Pathum Thani ' },
    { value: 'Ayutthaya', label: 'Ayutthaya' },
    { value: 'Phichit ', label: 'Phichit ' },
    { value: 'Phitsanulok ', label: 'Phitsanulok ' },
    { value: 'Phetchabun ', label: 'Phetchabun ' },
    { value: 'Lopburi ', label: 'Lopburi ' },
    { value: 'Samut Prakan', label: 'Samut Prakan' },
    { value: 'Samut Songkhram', label: 'Samut Songkhram' },
    { value: 'Samut Sakhon', label: 'Samut Sakhon' },
    { value: 'Sing Buri', label: 'Sing Buri' },
    { value: 'Sukhothai ', label: 'Sukhothai ' },
    { value: 'Suphan Buri', label: 'Suphan Buri' },
    { value: 'Saraburi', label: 'Saraburi' },
    { value: 'Ang Thong', label: 'Ang Thong' },
    { value: 'Uthai Thani', label: 'Uthai Thani' },
    { value: 'Chanthaburi', label: 'Chanthaburi' },
    { value: 'Chachoengsao ', label: 'Chachoengsao ' },
    { value: 'Chonburi ', label: 'Chonburi ' },
    { value: 'Trat ', label: 'Trat ' },
    { value: 'Prachinburi ', label: 'Prachinburi ' },
    { value: 'Rayong ', label: 'Rayong ' },
    { value: 'Sa Kaeo', label: 'Sa Kaeo' },
    { value: 'Kanchanaburi ', label: 'Kanchanaburi ' },
    { value: 'Tak ', label: 'Tak ' },
    { value: 'Prachuap Khiri Khan', label: 'Prachuap Khiri Khan' },
    { value: 'Phetchaburi ', label: 'Phetchaburi ' },
    { value: 'Ratchaburi ', label: 'Ratchaburi ' },
    { value: 'Chiang Mai ', label: 'Chiang Mai ' },
    { value: 'Chiang Rai  ', label: 'Chiang Rai  ' },
    { value: 'Lampang  ', label: 'Lampang  ' },
    { value: 'Lamphun ', label: 'Lamphun ' },
    { value: 'Mae Hong Son', label: 'Mae Hong Son' },
    { value: 'Nan ', label: 'Nan ' },
    { value: 'Phayao ', label: 'Phayao ' },
    { value: 'Phrae ', label: 'Phrae ' },
    { value: 'Uttaradit ', label: 'Uttaradit ' },
    { value: 'Kalasin ', label: 'Kalasin ' },
    { value: 'Khon Kaen', label: 'Khon Kaen' },
    { value: 'Chaiyaphum ', label: 'Chaiyaphum' },
    { value: 'Nakhon Phanom', label: 'Nakhon Phanom' },
    { value: 'Nakhon Ratchasima', label: 'Nakhon Ratchasima' },
    { value: 'Bueng Kan', label: 'Bueng Kan' },
    { value: 'Buriram ', label: 'Buriram ' },
    { value: 'Maha Sarakham', label: 'Maha Sarakham' },
    { value: 'Mukdahan', label: 'Mukdahan' },
    { value: 'Yasothon ', label: 'Yasothon ' },
    { value: 'Roi Et', label: 'Roi Et' },
    { value: 'Loei ', label: 'Loei ' },
    { value: 'Sakon Nakhon', label: 'Sakon Nakhon' },
    { value: 'Surin ', label: 'Surin ' },
    { value: 'Sisaket ', label: 'Sisaket ' },
    { value: 'Nong Khai', label: 'Nong Khai' },
    { value: 'Nong Bua Lamphu', label: 'Nong Bua Lamphu' },
    { value: 'Udon Thani', label: 'Udon Thani' },
    { value: 'Ubon Ratchathani', label: 'Ubon Ratchathani' },
    { value: 'Amnat Charoen', label: 'Amnat Charoen' },
    { value: 'Krabi', label: 'Krabi' },
    { value: 'Chumphon ', label: 'Chumphon ' },
    { value: 'Trang ', label: 'Trang ' },
    { value: 'Nakhon Si Thammarat', label: 'Nakhon Si Thammarat' },
    { value: 'Narathiwat ', label: 'Narathiwat ' },
    { value: 'Pattani ', label: 'Pattani ' },
    { value: 'Phang Nga', label: 'Phang Nga' },
    { value: 'Phatthalung ', label: 'Phatthalung ' },
    { value: 'Phuket ', label: 'Phuket ' },
    { value: 'Ranong', label: 'Ranong' },
    { value: 'Satun ', label: 'Satun ' },
    { value: 'Songkhla  ', label: 'Songkhla  ' },
    { value: 'Surat Thani ', label: 'Surat Thani ' },
    { value: 'Yala  ', label: 'Yala  ' },
  ];

export default LocationOptions;